import Header from "./common/Header"
import Footer from "./common/Footer"
import Layout from "./common/Layout"
import CartIcon from "./CartIcon"
import ProfileMenu from "./ProfileMenu"
import MobileNav from "./MobileNav"
import NavMenu from "./NavMenu"
import Hero from "./Hero"
import LatestCollection from "./LatestCollection"
import { Title, ThickTitleBorder, ThinTitleBorder, SubTitle } from "./Title"
import ProductsItem from "./ProductsItem"
import BestSeller from "./BestSeller"
import ProductsGrid from "./ProductsGrid"
import OurPolicy from "./OurPolicy"
import NewsLetterBox from "./NewsLetterBox"
import SearchBar from "./SearchBar"
import Filters from "./Filters"
import SortAndTitle from "./SortAndTitle"
import RelatedProduct from "./RelatedProduct"
import ProductImages from "./ProductImages"
import DescriptionReview from "./DescriptionReview"
import ProductInfo from "./ProductInfo"
import CartTotal from "./CartTotal"
import InputField from "./InputField"
import ToggleText from "./ToggleText"
import FeatureSection from "./FeatureSection"


export { Header, Footer, Layout, CartIcon, ProfileMenu, MobileNav, NavMenu, Hero, LatestCollection, Title, ThickTitleBorder, ThinTitleBorder, SubTitle, ProductsItem, BestSeller, ProductsGrid, OurPolicy, NewsLetterBox, SearchBar, Filters, SortAndTitle, RelatedProduct, ProductImages, DescriptionReview, ProductInfo, CartTotal, InputField, ToggleText, FeatureSection }  